# Blog
keywords: 个人博客,blog
author: 余鸿靖
description: 个人文章
avatar: /images/favicon.png

# Social Accounts
twitter: 
rss: 
weibo: 
instagram: 
github: https://github.com/yuhongjing
facebook: 

# Comment
duoshuo: 
disqus: 
gentie: 

menu:
  home: /
  categories: /categories
  about: /about
  archives: /archives
  tags: /鸡汤
  #schedule: /schedule
  #commonweal: /404.html
